#Exercício Prático — Análise de Qualidade do Ar no Brasil com Python

##Contexto do Problema
A poluição do ar é um problema crescente em diversas cidades brasileiras. O Ministério do Meio Ambiente
deseja analisar dados coletados por sensores ambientais instalados em diferentes capitais para entender:
- quais cidades apresentam maior concentração de poluentes
- quais períodos do ano apresentam pior qualidade do ar
- quais poluentes são mais críticos

#Parte 01
##Preparação do ambiente

In [43]:
import pandas as pd

In [44]:
df = pd.read_csv('/content/qualidade_ar_brasil.csv')

#Parte 02
##Inspeção inicial do dataset

In [45]:
df.head()
df.describe()

,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,26.597625,46.84950,27.537125,32.405125,25.640500,74.918750,47.758375
std,8.983311,13.63357,9.157577,9.247010,4.608675,9.492972,8.747129
min,6.000000,12.20000,5.000000,8.000000,14.500000,47.300000,28.600000
25%,20.400000,37.10000,21.700000,25.400000,22.300000,69.275000,41.600000
50%,25.900000,46.30000,26.800000,32.500000,25.850000,76.250000,46.900000
75%,32.000000,55.10000,32.900000,38.400000,29.100000,81.425000,53.500000
max,60.100000,91.60000,61.700000,68.100000,36.100000,96.000000,86.300000

##Perguntas

1. Quantas medições existem no dataset?<br>
800 medições

In [46]:
df.shape

(800, 11)

2. Quantas cidades estão presentes na base?<br>
10 cidades

In [47]:
df['cidade'].nunique()

10

3. Quais colunas representam poluentes atmosféricos?<br>
As colunas com pm25, pm10, no2 e o3

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 800 non-null    object
 1   cidade               800 non-null    object
 2   estado               800 non-null    object
 3   pm25                 800 non-null    float64
 4   pm10                 800 non-null    float64
 5   no2                  800 non-null    float64
 6   o3                   800 non-null    float64
 7   temperatura          800 non-null    float64
 8   umidade              800 non-null    float64
 9   indice_qualidade_ar  800 non-null    float64
 10  nivel_alerta         800 non-null    object
dtypes: float64(7), object(4)
memory usage: 68.9+ KB

4. Existem valores ausentes no dataset?<br>
Não

In [49]:
df.isnull().sum()

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

#Parte 03
##Análise por cidade

In [50]:
df['cidade'].unique()
df.groupby('cidade')[['pm25','pm10','no2','o3']].mean()

                     pm25       pm10        no2         o3
cidade
Belo Horizonte  27.874026  48.409091  27.992208  30.141558
Brasília        31.351724  59.428736  29.926437  33.167816
Curitiba        25.339785  43.408602  26.151613  28.435484
Fortaleza       23.186250  44.662500  24.232500  34.176250
Manaus          26.271084  46.898795  22.566265  30.354217
Porto Alegre    26.798592  47.760563  27.959155  27.991549
Recife          23.416471  41.165882  24.320000  32.205882
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145
Salvador        21.503896  39.102597  24.568831  34.274026
São Paulo       33.653125  56.256250  39.314062  34.878125

##Perguntas

1. Qual cidade apresenta maior média de PM2.5?<br>
São Paulo

In [51]:
df.groupby('cidade')['pm25'].mean().sort_values(ascending=False)

cidade
São Paulo         33.653125
Brasília          31.351724
Belo Horizonte    27.874026
Rio de Janeiro    27.825301
Porto Alegre      26.798592
Manaus            26.271084
Curitiba          25.339785
Recife            23.416471
Fortaleza         23.186250
Salvador          21.503896
Name: pm25, dtype: float64

2. Qual cidade apresenta maior média de NO2?<br>
São Paulo

In [52]:
df.groupby('cidade')['no2'].mean().sort_values(ascending=False)

cidade
São Paulo         39.314062
Rio de Janeiro    30.925301
Brasília          29.926437
Belo Horizonte    27.992208
Porto Alegre      27.959155
Curitiba          26.151613
Salvador          24.568831
Recife            24.320000
Fortaleza         24.232500
Manaus            22.566265
Name: no2, dtype: float64

3. Existe alguma cidade com níveis consistentemente mais altos de poluentes?<br>
A julgar que a cidade de São Paulo apresenta um conjunto de média maior que as demais, ela foi a escolhida

In [53]:
df.groupby('cidade')[['pm25','pm10','no2','o3']].mean()

                     pm25       pm10        no2         o3
cidade
Belo Horizonte  27.874026  48.409091  27.992208  30.141558
Brasília        31.351724  59.428736  29.926437  33.167816
Curitiba        25.339785  43.408602  26.151613  28.435484
Fortaleza       23.186250  44.662500  24.232500  34.176250
Manaus          26.271084  46.898795  22.566265  30.354217
Porto Alegre    26.798592  47.760563  27.959155  27.991549
Recife          23.416471  41.165882  24.320000  32.205882
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145
Salvador        21.503896  39.102597  24.568831  34.274026
São Paulo       33.653125  56.256250  39.314062  34.878125

#Parte 04
##Análise do índice de qualidade do ar

In [54]:
df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values(ascending=False)

cidade
São Paulo         59.345312
Brasília          54.955172
Rio de Janeiro    50.639759
Belo Horizonte    48.344156
Porto Alegre      46.898592
Manaus            45.092771
Fortaleza         44.646250
Curitiba          44.359140
Recife            43.198824
Salvador          42.342857
Name: indice_qualidade_ar, dtype: float64

##Perguntas

1. Qual cidade apresenta pior qualidade média do ar?<br>
Analisando a tabela acima, temos que a cidade com a pior qualidade do ar é Salvador

2. Qual cidade apresenta melhor qualidade do ar?<br>
Analisando a tabela acima, temos que a cidade de São Paulo apresenta a melhor qualidade do ar

#Parte 05
##Filtragem por nível de alerta

In [55]:
df_alerta = df[df['nivel_alerta'].isin(['Ruim','Muito Ruim'])]
df_alerta.head()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
235,2025-04-20,São Paulo,SP,33.7,73.7,57.2,34.3,25.9,61.1,70.8,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim

##Perguntas

1. Quantos registros possuem alerta crítico?<br>
A julgar que não tem um nível de alerta "crítico", considerarei que o pedido é referente aos níveis "ruim" e "muito ruim". Neste caso, são 14 registros

In [56]:
df.groupby('nivel_alerta')['nivel_alerta'].count()

nivel_alerta
Bom         150
Moderado    636
Ruim         14
Name: nivel_alerta, dtype: int64

2. Em quais cidades eles ocorrem com maior frequência?<br>
A cidade de São Paulo é a mais frequente, seguido do Rio de Janeiro e Brasília. Finalizando com Belo Horizonte e Manaus

In [57]:
df[df['nivel_alerta'].isin(['Ruim', 'Muito Ruim'])].groupby('cidade')['nivel_alerta'].count().sort_values(ascending=False)

cidade
São Paulo         8
Rio de Janeiro    2
Brasília          2
Belo Horizonte    1
Manaus            1
Name: nivel_alerta, dtype: int64

#Parte 06
##Ranking dos dias mais críticos

In [58]:
df.sort_values('indice_qualidade_ar', ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim

##Perguntas

1. Qual foi o pior dia registrado?<br>
Considerando que o "pior dia" diz respeito a qualidade do ar, este dia foi 19/08/2025 na cidade de São Paulo

2. Em qual cidade ocorreu?<br>
Cidade de São Paulo

3. Quais poluentes estavam mais altos nesse dia?<br>
Considerando os valores médios, calculados anteriormente, todos os poluentes (pm25, pm10, no2 e 03) estão acima da média, portanto, mais altos

#Parte 07
##Análise temporal

In [59]:
df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month
df.groupby('mes')['indice_qualidade_ar'].mean()

mes
1     44.852308
2     42.985714
3     46.675949
4     47.559259
5     47.107813
6     52.881034
7     51.293443
8     49.640000
9     49.923333
10    47.865385
11    46.861429
12    45.829333
Name: indice_qualidade_ar, dtype: float64

##Perguntas

1. Em quais meses a qualidade do ar tende a ser pior?<br>
A qualidade tende a ser pior em fevereiro, janeiro e dezembro

In [60]:
df.groupby('mes')['indice_qualidade_ar'].mean().sort_values()

mes
2     42.985714
1     44.852308
12    45.829333
3     46.675949
11    46.861429
5     47.107813
4     47.559259
10    47.865385
8     49.640000
9     49.923333
7     51.293443
6     52.881034
Name: indice_qualidade_ar, dtype: float64

2. Existe algum padrão sazonal?<br>
Analisando os dados, ele tende a ser pior no verão, categorizado pelas altas temperaturas

#Parte 08
##Correlação entre variáveis

In [61]:
df[['temperatura','pm25','pm10','no2','o3']].corr()

             temperatura      pm25      pm10       no2        o3
temperatura     1.000000 -0.114987 -0.112821 -0.168689  0.160547
pm25           -0.114987  1.000000  0.253494  0.124651  0.022676
pm10           -0.112821  0.253494  1.000000  0.151211 -0.002501
no2            -0.168689  0.124651  0.151211  1.000000  0.048104
o3              0.160547  0.022676 -0.002501  0.048104  1.000000

##Perguntas

1. Existe correlação entre temperatura e poluição?<br>
Considerando que quanto mais próximo a 0, eles tendem a ser menos correlacionados, temos que a temperatura não tem correlação, ou bem pouca, com nenhuma poluição

2. Quais poluentes parecem mais relacionados entre si?<br>
Os únicos poluentes que tem um grau de correlação maior, mais ainda assim não muito alto, são as partículas pm2.5 e pm10

#Desafio Final
##Relatório para o Ministro

1. Qual cidade apresenta pior qualidade média do ar?<br>
A cidade de Salvador

2. Quais poluentes são mais críticos?<br>
PM10 e O3

In [62]:
df[['pm25', 'pm10', 'no2', 'o3']].mean().sort_values(ascending=False)

pm10    46.849500
o3      32.405125
no2     27.537125
pm25    26.597625
dtype: float64

3. Existem meses mais problemáticos?<br>
Os meses mais problemáticos são os meses do verão

4. Quais cidades deveriam receber maior atenção das autoridades ambientais?<br>
São Paulo, Rio de Janeiro e Brasília