In [40]:
import numpy as np
import pandas as pd

In [41]:
# Base de vendas
dados_vendas = {
    'cliente_id': [101, 102, 103, 101, 104, 102, 105, 103],
    'valor': [3500.75, 189.50, np.nan, 1200.00, 450.00, np.nan, 89.90, 780.50],
    'categoria': [
        'Eletronicos',
        'Livros',
        'Roupas',
        'Eletronicos',
        'Automotivo',
        'Livros',
        'Roupas',
        'Roupas',
    ],
    'data_hora': [
        '2024-01-15 10:23:00',
        '2024-01-18 14:05:00',
        '2024-02-05 09:12:00',
        '2024-02-20 16:40:00',
        '2024-03-02 11:00:00',
        '2024-03-15 18:30:00',
        '2024-04-10 08:20:00',
        '2024-04-22 13:45:00',
    ],
    'status': [
        'Concluído',
        'Concluído',
        'Pendente',
        'Concluído',
        'Cancelado',
        'Concluído',
        'Concluído',
        'Concluído',
    ],
    'email': [
        'maria@gmail.com',
        'joao@outlook.com',
        'ana@yahoo.com',
        'maria@gmail.com',
        'carlos@gmail.com',
        'joao@outlook.com',
        'lucas@empresa.com.br',
        'ana@yahoo.com',
    ],
}

# Base de clientes
dados_clientes = {
    'cliente_id': [101, 102, 103, 104, 105],
    'nome': [
        'Maria Silva',
        'Joao Souza',
        'Ana Oliveira',
        'Carlos Lima',
        'Lucas Mendes',
    ],
    'cidade': [
        'Sao Paulo',
        'Rio de Janeiro',
        'Belo Horizonte',
        'Curitiba',
        'Salvador',
    ],
}

In [42]:
df_vendas = pd.DataFrame(dados_vendas)
df_clientes = pd.DataFrame(dados_clientes)

##Parte 01
#Diagnostico e Limpeza
- Inspecione as dimensões e o resumo dos tipos de dados do DataFrame df_vendas usando .shape e .info().
- Identifique os valores nulos e preencha os registros ausentes da coluna valor utilizando a mediana da respectiva categoria ou a mediana global com .fillna().
- Filtre e exiba apenas as transações com status 'Concluído' e valor superior a R$ 500,00 usando .loc[] ou .query().

In [43]:
dimensoes = df_vendas.shape
df_vendas.info()

print(f"Dimensão dos dados de venda: {dimensoes}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  8 non-null      int64
 1   valor       6 non-null      float64
 2   categoria   8 non-null      object
 3   data_hora   8 non-null      object
 4   status      8 non-null      object
 5   email       8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes
Dimensão dos dados de venda: (8, 6)

In [44]:
mediana_global = df_vendas['valor'].median()

df_vendas['valor'] = df_vendas['valor'].fillna(df_vendas.groupby('categoria')['valor'].transform('median')).fillna(mediana_global)

In [45]:
df_vendas.loc[(df_vendas['status'] == 'Concluído') & (df_vendas['valor'] > 500)]

,cliente_id,valor,categoria,data_hora,status,email
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com

##Parte 2
#Cruzamento e Transformação (Intermediário)
- Realize uma junção relacional (left merge) entre df_vendas e df_clientes utilizando a chave cliente_id.
- Crie uma nova coluna chamada media_categoria contendo o valor médio de vendas por categoria sem reduzir o número de linhas do DataFrame (utilize .groupby() com .transform()).
- Identifique quantos clientes usam o provedor de e-mail @gmail.com através do acessor de texto .str.contains().

In [46]:
left_merge = pd.merge(df_vendas, df_clientes, on='cliente_id', how='left')
left_merge

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba
5,102,189.50,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
6,105,89.90,Roupas,2024-04-10 08:20:00,Concluído,lucas@empresa.com.br,Lucas Mendes,Salvador
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com,Ana Oliveira,Belo Horizonte

In [47]:
media_categoria = df_vendas.groupby('categoria')['valor'].transform('mean')
df_vendas['media_categoria'] = media_categoria
df_vendas

,cliente_id,valor,categoria,data_hora,status,email,media_categoria
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,2350.375
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,189.500
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,435.200
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,2350.375
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,450.000
5,102,189.50,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com,189.500
6,105,89.90,Roupas,2024-04-10 08:20:00,Concluído,lucas@empresa.com.br,435.200
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com,435.200

In [48]:
left_merge['email'].str.contains('@gmail.com').sum()

np.int64(3)

##Parte 3
#Análise Temporal e Agregação (Intermediário)
- Converta a coluna data_hora para o tipo datetime nativo com pd.to_datetime() e extraia o mês por extenso ou o nome do dia da semana utilizando o acessor .dt.
- Construa uma tabela dinâmica com pd.pivot_table() apresentando o total (sum) do valor de vendas agrupado por categoria nas linhas e por cidade nas colunas, preenchendo eventuais valores nulos com zero.

In [49]:
df_vendas['data_hora'] = pd.to_datetime(df_vendas['data_hora'])
df_vendas['mes'] = df_vendas['data_hora'].dt.strftime('%B')
df_vendas['dia_semana'] = df_vendas['data_hora'].dt.strftime('%A')
df_vendas

,cliente_id,valor,categoria,data_hora,status,email,media_categoria,mes,dia_semana
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,2350.375,January,Monday
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,189.500,January,Thursday
2,103,435.20,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,435.200,February,Monday
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,2350.375,February,Tuesday
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,450.000,March,Saturday
5,102,189.50,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com,189.500,March,Friday
6,105,89.90,Roupas,2024-04-10 08:20:00,Concluído,lucas@empresa.com.br,435.200,April,Wednesday
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com,435.200,April,Monday

In [51]:
tabela_dinamica = pd.pivot_table(left_merge, values='valor', index='categoria', columns='cidade', aggfunc='sum', fill_value=0)